const jwt = require("jsonwebtoken")

// Return the token generated by jwt.verify().

const generateToken = (userId) => {
  const token = jwt.sign(
    { userId }, // token identification
    process.env.JWT_SECRET, // secret phrase
    { expiresIn: "2 days" } // options
  )

  return token
}

module.exports = generateToken
